<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\RaceEvent;

/**
 * RaceEventAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceEventAttributeRepository extends BaseRepository
{
    
    public function findByRaceEvent(RaceEvent $raceEvent) 
    {
        $qb = $this->getQB();
        $qb->join('r.raceEvents', 're');
        $qb->andWhere('re = :raceEvent')->setParameter('raceEvent', $raceEvent);
        $result = $qb->getQuery()->getResult();
        
        return $result;
    }
}
