<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RaceEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceEventRepository extends BaseRepository
{
    /**
     * @return int
     */
    public function getCount()
    {
        $qb = $this->getQB();
        $qb->select('count(r.id)');
        $count = $qb->getQuery()->getSingleScalarResult();

        return $count;
    }
}
