<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RaceRepository extends BaseRepository
{
}
