<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Region;
use CrEOF\Spatial\PHP\Types\Geometry\Point;


/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends BaseRepository
{
    public function getOrCreateRegion($mapboxID, $name, $latitude, $longitude) 
    {
        $region = $this->findOneBy([
            'mapboxID' => $mapboxID,
        ]);
        
        if ($region === null) {
            $point = new Point($longitude, $latitude, 4326);
            $region = new Region();
            $region->setName($name);
            $region->setMapboxID($mapboxID);
            $region->setCoords($point);
            $this->add($region);
            $this->store();
        }
        
        return $region;
    }
    
}
