imports:
    - { resource: parameters.yml }
    - { resource: parameters.php }
    - { resource: security.yml }
    - { resource: services.yml }

# Vendor configs
    - { resource: vendor/fos_rest.yml }
    - { resource: vendor/fos_user.yml }
    - { resource: vendor/stof_doctrine_extensions.yml }
    - { resource: vendor/knp_gaufrette.yml }
    - { resource: vendor/nelmio_cors.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    search_index_name: 'search'
    autosuggest_index_name: 'autosuggest'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum: string
        types:
            # add and postgis types as provided by creof/doctrine2-spatial package
            geometry:               CrEOF\Spatial\DBAL\Types\GeometryType
            point:                  CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:                CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring:             CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
            # add hstore type from http://github.com/easybiblabs/EasyBib_DoctrineTypes
            hstore:                 EasyBib\Doctrine\Types\Hstore
            MIMEType:               AppBundle\DBAL\Types\MIMEType
            RaceType:               AppBundle\DBAL\Types\RaceType
            RaceCategory:           AppBundle\DBAL\Types\RaceCategory
            RaceDistance:           AppBundle\DBAL\Types\RaceDistance

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # postgis functions as provided by creof/doctrine2-spatial package
        dql:
            numeric_functions:
                st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                st_distance:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                st_area:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                st_length:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                st_centroid:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STCentroid
                st_astext:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
                st_makeline:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakeLine
                st_setsrid:      CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STSetSRID

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
