# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email  # use email as login

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern:  ^/v2/user/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /v2/user/login
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/v2/user
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/v2/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/user/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/user/confirm, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/user/password/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/user/password/request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/user/profile, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v2/user, roles: IS_AUTHENTICATED_FULLY }
