app:
    container_name: tb_api_app
    build: app
    volumes:
        - ./../:/var/www
    tty: true

php:
    container_name: tb_api_php
    build: php
    expose:
        - 9000
    volumes_from:
        - app
    links:
        - postgres
        - elasticsearch

postgres:
    container_name: tb_api_postgres
    # build: postgres
    image: camptocamp/postgis
    ports:
        - 5432:5432
    environment:
        POSTGRES_PASSWORD: trailburning
        POSTGRES_DB: trailburning
        POSTGRES_USER: trailburning

nginx:
    container_name: tb_api_nginx
    build: nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    volumes:
        - ./../var/logs/nginx/:/var/log/nginx

elasticsearch:
    container_name: tb_api_elasticsearch
    build: elasticsearch
    environment:
         - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports: 
        - 9200:9200
        
kibana:
    container_name: tb_api_kibana
    image: ditointernet/docker-kibana-sense
    ports: 
        - 5601:5601
    links:
        - elasticsearch
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
        SENSE.DEFAULT_SERVER_URL: http://elasticsearch:9200

    