default:
    resource: AppBundle\Controller\DefaultController
    
swagger:
    path:   /v2/swagger.json
    defaults: { _controller: AppBundle:Swagger:index, _format: json }
    
status:
    type:   rest
    resource: AppBundle\Controller\StatusController
    prefix: /v2
    
journeys:
    type:   rest
    resource: AppBundle\Controller\JourneysController
    prefix: /v2
    
events:
    type:   rest
    resource: AppBundle\Controller\EventsController
    prefix: /v2
    
assets:
    type:   rest
    resource: AppBundle\Controller\AssetsController
    prefix: /v2