autosuggest:
    resource: "AppBundle\Controller\AutosuggestController"
    type: rest
    prefix: /v2

search:
    resource: "AppBundle\Controller\SearchController"
    type: rest
    prefix: /v2

race:
    resource: "AppBundle\Controller\RaceController"
    type: rest
    prefix: /v2

race_event_attributes:
    resource: "AppBundle\Controller\RaceEventAttributeController"
    type:  rest
    prefix: /v2

race_events:
    resource: "AppBundle\Controller\RaceEventController"
    type:  rest
    prefix: /v2

default:
    resource: AppBundle\Controller\DefaultController
    
swagger:
    path:   /v2/swagger.json
    defaults: { _controller: AppBundle:Swagger:index, _format: json }
    
status:
    type:   rest
    resource: AppBundle\Controller\StatusController
    prefix: /v2
    
journeys:
    type:   rest
    resource: AppBundle\Controller\JourneysController
    prefix: /v2
    
events:
    type:   rest
    resource: AppBundle\Controller\EventsController
    prefix: /v2
    
assets:
    type:   rest
    resource: AppBundle\Controller\AssetsController
    prefix: /v2
    
asset_medias:
    type:   rest
    resource: AppBundle\Controller\AssetsMediaController
    prefix: /v2
    
race_event_medias:
    type:   rest
    resource: AppBundle\Controller\RaceEventMediaController
    prefix: /v2
