services:
    
    tb.swaggerBridge:
        class: AppBundle\Services\SwaggerBridge
        arguments: 
            - %kernel.root_dir%
            - %kernel.environment%
            - %kernel.debug%
            
    tb.journey:
        class: AppBundle\Services\JourneyService
        arguments: 
            - @tb.journey.repository
            - @tb.user.repository
            - @tb.response.builder
            - @tb.gpxParser
            - @tb.routePoint.repository
            
    tb.journey.repository:
        class: AppBundle\Repository\JourneyRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Journey
    
    tb.listener.apiResponse:
        class: AppBundle\Listener\APIResponseListener
        tags:
            - { name: "kernel.event_listener", event: "kernel.view", method: "onKernelView", priority: 100 }
            
    tb.user.repository:
        class: AppBundle\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\User
            
    tb.response.builder:
        class: AppBundle\Response\APIResponseBuilder
    
    tb.asset:
        class: AppBundle\Services\AssetService
        arguments: 
            - @tb.asset.repository
            - @tb.event.repository
            - @tb.response.builder
        
    tb.asset.repository:
        class: AppBundle\Repository\AssetRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Asset
            
    tb.media.repository:
        class: AppBundle\Repository\MediaRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Media

    tb.event:
        class: AppBundle\Services\EventService
        arguments: 
            - @tb.event.repository
            - @tb.journey.repository
            - @tb.response.builder
            
    tb.event.repository:
        class: AppBundle\Repository\EventRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Event

    tb.gpxParser:
        class: AppBundle\Services\GPXParser
        
    tb.routePoint.repository:
        class: AppBundle\Repository\RoutePointRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\RoutePoint
            
    tb.media:
        class: AppBundle\Services\MediaService
        arguments: 
            - @media_filesystem
            - @tb.media.repository
            - @tb.response.builder
            - @tb.asset.repository
            - @tb.media.analyzer
            - @tb.mediaAttribute.repository
            
    tb.s3Client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: %aws_accesskey%
                secret: %aws_secretkey%
                region: %aws_region%
                version: 'latest'

    tb.media.analyzer:
        class: AppBundle\Services\MediaAnalyzer
        arguments:
            -
                'image/jpeg': @tb.media.metadata.jpeg
                'audio/mpeg': @tb.media.metadata.mp3
                'video/mp4': @tb.media.metadata.mpeg
                
    tb.media.metadata.jpeg:
        class: AppBundle\Services\MetadataReader\JPEGMetadataReader
    
    tb.media.metadata.mp3:
        class: AppBundle\Services\MetadataReader\MPEGMetadataReader
        
    tb.media.metadata.mpeg:
        class: AppBundle\Services\MetadataReader\MP4MetadataReader
        
    tb.mediaAttribute.repository:
        class: AppBundle\Repository\MediaAttributeRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\MediaAttribute