services:
    app.swaggerBridge:
        class: AppBundle\Services\SwaggerBridge
        arguments:
            - '%kernel.root_dir%'
            - '%kernel.environment%'
            - '%kernel.debug%'
    app.journey:
        class: AppBundle\Services\JourneyService
        arguments:
            - '@app.journey.repository'
            - '@app.user.repository'
            - '@app.response.builder'
            - '@app.gpxParser'
            - '@app.routePoint.repository'
            - '@form.factory'
            - '@router'
    app.journey.repository:
        class: AppBundle\Repository\JourneyRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Journey
    app.listener.apiResponse:
        class: AppBundle\Listener\APIResponseListener
        tags:
            -
                name: kernel.event_listener
                event: kernel.view
                method: onKernelView
                priority: 100
    app.user.repository:
        class: AppBundle\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\User
    app.response.builder:
        class: AppBundle\Services\APIResponseBuilder
        arguments:
            - '@validator'
    app.asset:
        class: AppBundle\Services\AssetService
        arguments:
            - '@app.asset.repository'
            - '@app.event.repository'
            - '@app.response.builder'
            - '@app.assetCategory.repository'
            - '@form.factory'
            - '@router'
    app.asset.repository:
        class: AppBundle\Repository\AssetRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Asset
    app.assetCategory.repository:
        class: AppBundle\Repository\AssetCategoryRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\AssetCategory
    app.media.repository:
        class: AppBundle\Repository\MediaRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Media
    app.event:
        class: AppBundle\Services\EventService
        arguments:
            - '@app.event.repository'
            - '@app.journey.repository'
            - '@app.response.builder'
            - '@form.factory'
            - '@router'
            - '@app.eventCustom.repository'
    app.event.repository:
        class: AppBundle\Repository\EventRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\Event
    app.gpxParser:
        class: AppBundle\Services\GPXParser
    app.routePoint.repository:
        class: AppBundle\Repository\RoutePointRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\RoutePoint
    app.media:
        class: AppBundle\Services\MediaService
        arguments:
            - '@media_filesystem'
            - '@app.media.repository'
            - '@app.response.builder'
            - '@app.asset.repository'
            - '@app.media.analyzer'
            - '@app.mediaAttribute.repository'
    app.s3Client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: factory
        arguments:
            -
                region: '%aws_region%'
                version: latest
                credentials: { key: '%aws_accesskey%', secret: '%aws_secretkey%' }
    app.media.analyzer:
        class: AppBundle\Services\MediaAnalyzer
        arguments:
            -
                image/jpeg: '@app.media.metadata.jpeg'
                audio/mpeg: '@app.media.metadata.mp3'
                video/mp4: '@app.media.metadata.mpeg'
                video/x-m4v: '@app.media.metadata.mpeg'
    app.media.metadata.jpeg:
        class: AppBundle\Services\MetadataReader\JPEGMetadataReader
    app.media.metadata.mp3:
        class: AppBundle\Services\MetadataReader\MPEGMetadataReader
    app.media.metadata.mpeg:
        class: AppBundle\Services\MetadataReader\MP4MetadataReader
    app.mediaAttribute.repository:
        class: AppBundle\Repository\MediaAttributeRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\MediaAttribute
    app.eventCustom.repository:
        class: AppBundle\Repository\EventCustomRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle\Entity\EventCustom
    app.handler.race_event:
        class: AppBundle\Handler\RaceEventHandler
        arguments:
            - '@app.repository.race_event'
            - '@app.services.response_builder'
            - '@form.factory'
            - '@router'
    app.services.response_builder:
        class: AppBundle\Services\APIResponseBuilder
        arguments:
            - '@validator'
    app.repository.race_event:
        class: AppBundle\Repository\RaceEventRepository
        arguments:
            - AppBundle\Entity\RaceEvent
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
    app.handler.race:
        class: AppBundle\Handler\RaceHandler
        arguments:
            - '@app.repository.race'
            - '@app.services.response_builder'
            - '@form.factory'
            - '@router'
    app.repository.race:
        class: AppBundle\Repository\RaceRepository
        arguments:
            - AppBundle\Entity\Race
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository

    app.factory.elasticsearch.client:
        class: AppBundle\Factory\ElasticsearchClientFactory

    vendor.elasticsearch.client:
        class: Elasticsearch\Client
        factory: ["@app.factory.elasticsearch.client", create]
        arguments: 
            - %elasticsearch%
            
    app.handler.search:
        class: AppBundle\Handler\SearchHandler
        arguments:
            - '@app.services.response_builder'
            - '@app.services.search'
    
    app.services.search:
        class: AppBundle\Services\SearchService
        arguments:
            - '@vendor.elasticsearch.client'
